---
id: Nls
name: Nls
full: Native language support library
description: >
  Common methods for handling language data, timezones, and hostname->country
  lookups.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Nls
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 2.2.2
  api: 1.3.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.php.net/Net_DNS2: '*'
      pecl.php.net/geoip: '*'
