<?php

declare(strict_types=1);

/**
 * Copyright 1999-2026 Horde LLC (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (LGPL). If you
 * did not receive this file, see http://www.horde.org/licenses/lgpl21.
 *
 * @category  Horde
 * @license   http://www.horde.org/licenses/lgpl21 LGPL 2.1
 * @package   Nls
 */

namespace Horde\Nls\DataRegeneration;

use Horde\Nls\Countries;
use RuntimeException;

/**
 * CLI utility to fetch the IANA TLD list and classify entries into ccTLDs
 * and generic TLDs by cross-referencing against the Countries class.
 *
 * The output can be pasted into the Tld class to keep the generic TLD list
 * up to date.
 *
 * @category  Horde
 * @license   http://www.horde.org/licenses/lgpl21 LGPL 2.1
 * @package   Nls
 */
class IanaTldUpdater
{
    private const IANA_URL = 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt';

    public function __construct(
        private readonly Countries $countries,
    ) {}

    /**
     * Fetches and parses the IANA TLD list.
     *
     * Returns an associative array with two keys:
     * - 'ccTlds': array of 2-letter TLDs that exist in the Countries list
     * - 'genericTlds': array of all other TLDs
     *
     * @return array{ccTlds: list<string>, genericTlds: list<string>}
     *
     * @throws RuntimeException If the IANA list cannot be fetched.
     */
    public function fetch(): array
    {
        $context = stream_context_create([
            'http' => [
                'header' => 'User-Agent: HordeNls/1.0 (https://www.horde.org/)',
            ],
        ]);

        $content = file_get_contents(self::IANA_URL, false, $context);

        if ($content === false) {
            throw new RuntimeException('Failed to fetch IANA TLD list from ' . self::IANA_URL);
        }

        $lines = explode("\n", trim($content));
        $ccTlds = [];
        $genericTlds = [];

        foreach ($lines as $line) {
            $line = trim($line);

            // Skip empty lines and comments
            if ($line === '' || str_starts_with($line, '#')) {
                continue;
            }

            $tld = strtolower($line);
            $upper = strtoupper($tld);

            // A ccTLD is a 2-letter code that exists in the Countries list
            if (strlen($tld) === 2 && isset($this->countries[$upper])) {
                $ccTlds[] = $tld;
            } else {
                $genericTlds[] = $tld;
            }
        }

        sort($ccTlds);
        sort($genericTlds);

        return [
            'ccTlds' => $ccTlds,
            'genericTlds' => $genericTlds,
        ];
    }

    /**
     * Fetches the IANA TLD list and outputs the generic TLD list as a PHP
     * constant definition to stdout.
     */
    public function run(): void
    {
        $result = $this->fetch();
        $genericTlds = $result['genericTlds'];

        echo "/**\n";
        echo " * Generic TLDs (non-country-code) from IANA.\n";
        echo " *\n";
        echo " * Auto-generated by " . self::class . "\n";
        echo " */\n";
        echo "private const GENERIC_TLDS = [\n";

        foreach ($genericTlds as $tld) {
            echo "    '" . $tld . "',\n";
        }

        echo "];\n";
    }

    /**
     * CLI entry point.
     */
    public static function main(): void
    {
        $updater = new self(new \Horde\Nls\Countries());
        $updater->run();
    }
}
